sudo: required
language: node_js
node_js: 8
services:
- docker
before_install:
- mkdir -p /tmp/ts3
- cp -r ts3/* /tmp/ts3/
- sudo chown -R 503:503 /tmp/ts3
- docker-compose -f docker-compose.travis.yml up -d
- docker-compose -f docker-compose.travis.yml ps
- docker-compose -f docker-compose.travis.yml logs
deploy:
  provider: npm
  email: admin@cmr1.com
  on:
    tags: true
    repo: cmr1/node-ts3-bot
  api_key:
    secure: B1GxGmekOwpsCydS1yD+QyNkKAlJCk+NCMW9DD9DesPfme+tTuad6UYVFjb0mnrundY8Crmy8EauXEfLVZT0PSKBH7Uf6YIMdX+oZUmki6Both9nTjc1e9cmaCXcCHhzuXx5raN51wO3InNzno6k3dtFhPRyzyQDBJ1GOVWKbYQcNYFTdyaGIGiQhoA4SbTLtyEO8CTDBBrTa6+/H3iQAYj+5guuPtnyDk2Sf80+MUJZ07TxAjKyKUT0FezU6frDocoXJnVLl6Ci1tqgw/lTCvTblCS9zrISIKHDyz5U13zrTKZJ4D3fNQM3kyDzXB2awzP5nDFUeWK+Wrkarb9h0x6Xyzg5xpWH2U/5zUKo9pK7G34PrFM8yO7cKPSTW0htYS9v+3tvmgil7op0NhTqPpyBx9PeQzgBzNy9z/ErMPIhM2Eb8ggs87IIFrt7OesgS3ILPUkdXxXmOolOU9BVbWdLd0TTWuxSKQkfe8/x5FDJNX96QLYHIOKH4V34sK/tD/DldzEmpB5yi5JPNBJAaLEd1uC3bWkOk5Sz8z9jaRJp9+XbWCvJt/IDA4+TgaGRm76AvguI3pe8wzR3PCQScIUyLv8UCXNMlNEBLuIIt0zQ6LKAqCAtigEpyhMEAVr992TLBp/bZS6pbWEJJMT5Bpy0oOq/aY3zW7hRkrJx7G8=
notifications:
  slack:
    secure: pZyLZWwcMA2fnNXGC7MmvBVjLZLcOvKnenRXVubY1UdPUkugtprVLDGG28twICHr3eLfJx6NOGquDzklKneD9qZVJ289uJFotc0b1W2PeeIm1iuBD+/mpid9mHmqISdrS5gX/Cv4RzL/Xp92+dMax9JRVKhrBNfDuNA4HNnuac59pj9ufFulK6LZ2fAqzU+ftL4TeLsNszID9aGZ52IOTvEBClj0xespTTOaxMeM1OgHDW87vfGsDog9DaiiCW/Z774L6bEhJifVsB0f2m3PMirepGZHMPCC54ncRi/+o34+fQLOLdfN0y/aXaDoC3Wx0u3FwRqw+uJX11CCMJgGeEdDfTEN/hZ93jDVcK/fWrpommo6LrUBc4K2KRIyPtFgUoMfnm9Cu6Re0zO2SXm++92kSYZpcmYIvC55cZtNSOC6xY6icm1XPdofe+Os3lqQekZXVSqw+pUL6i8ayfaLJV4z6CJQkE4CcInlCxsJUg4YItldKxJDLL7tKjAwUowG1M2dilzuJdbCQjk8dDsZk0KHwO+m8KBdvfyZilV8M+3MmWJ+9ZkQe+XtSIYnXolThk3qkkGhBUUQkJ87Ee9Zo4S+baNJzQiBB3B0zw04ELqtSvAXxgp7pXXtk0YKmpTv27kfH7WN/AS4aVt9z7dHA2eoHHhDm6y7s1ZW5ZTazbQ=
