sudo: required
language: node_js
node_js: 6
services:
- docker
before_install:
- mkdir -p /tmp/ts3
- cp -r ts3/* /tmp/ts3/
- sudo chown -R 503:503 /tmp/ts3
- docker-compose -f docker-compose.travis.yml up -d
- docker-compose -f docker-compose.travis.yml ps
- docker-compose -f docker-compose.travis.yml logs
deploy:
  provider: npm
  email: admin@cmr1.com
  on:
    tags: true
    repo: cmr1/node-ts3-bot
  api_key:
    secure: Yzw6z81qG2zps8PP0HnG/3gO07brFbtlI1vPqNNeJjjRyWAHIxvFdJVtVBlFa6fyo1phjW5HN7+O93famhdHWOXTd35O2M70khqd5FvsZG9AdN+2tagWJO1oGDtk5CHA7jTnCp1d/BAf8b+MDw2BeKhS8uegb9sKoJ4LalCvcN4Z2V1vOX6GmaK0Qo8EAoss+gDc2BmpmZqhI+wXoyifwIKCF7+j3/pQ8Ub7SUJiTwOia07G0umln0+Q4xWbozcQWQXegvKq63IQY6rni1zvg7zKEm6/5Uo94La3DZ1VbEZ1K6K0e6rjYut65rxMShia9BmU2tuk9UqwJe3A1lMG45KODAoMb0TMRAPnhDsB6392rSKE/cFBi9rdlsGpAn+xx6YaBd/W+jNienmnp58IheGSNrYyRoYFJBx+OJk8IE0QUCyUZCj1sOQ8OaLNKetUDywgVYPbGErto0QvbrD/7aVoK+ragLkBZYWj2c3jOx5Tpug9/FurIpFbZ4J56UiC3lT74vhiFq+esawTWT16/uVkp5Kuv3SGo1JcJm9bPrhlptIHkkGAJ+VpQBQUzuhR/T/pVQi9yTRbxCp51d6BkHAVdAccdL3nw2psg0mCB7WhMCKAmlcMbWfQnoa9pv9vOUxI/8d1lUCs25QCq/2FBLXPm0VOjQfJ0lU+KcHqjFo=
notifications:
  slack:
    secure: pZyLZWwcMA2fnNXGC7MmvBVjLZLcOvKnenRXVubY1UdPUkugtprVLDGG28twICHr3eLfJx6NOGquDzklKneD9qZVJ289uJFotc0b1W2PeeIm1iuBD+/mpid9mHmqISdrS5gX/Cv4RzL/Xp92+dMax9JRVKhrBNfDuNA4HNnuac59pj9ufFulK6LZ2fAqzU+ftL4TeLsNszID9aGZ52IOTvEBClj0xespTTOaxMeM1OgHDW87vfGsDog9DaiiCW/Z774L6bEhJifVsB0f2m3PMirepGZHMPCC54ncRi/+o34+fQLOLdfN0y/aXaDoC3Wx0u3FwRqw+uJX11CCMJgGeEdDfTEN/hZ93jDVcK/fWrpommo6LrUBc4K2KRIyPtFgUoMfnm9Cu6Re0zO2SXm++92kSYZpcmYIvC55cZtNSOC6xY6icm1XPdofe+Os3lqQekZXVSqw+pUL6i8ayfaLJV4z6CJQkE4CcInlCxsJUg4YItldKxJDLL7tKjAwUowG1M2dilzuJdbCQjk8dDsZk0KHwO+m8KBdvfyZilV8M+3MmWJ+9ZkQe+XtSIYnXolThk3qkkGhBUUQkJ87Ee9Zo4S+baNJzQiBB3B0zw04ELqtSvAXxgp7pXXtk0YKmpTv27kfH7WN/AS4aVt9z7dHA2eoHHhDm6y7s1ZW5ZTazbQ=
