sudo: required
group: edge
language: node_js
node_js: 6
services:
- docker
before_install:
- docker-compose build
- docker-compose up -d
- docker-compose ps
- docker-compose logs
deploy:
  provider: npm
  email: admin@cmr1.com
  api_key:
    secure: pANSDv5hoeYhA0UvK3vCC/GXfymZcSa3imPJmihtNzyQ3OpOgDAybXpkREBBZ19enEmd8PGC1S7qDzZml1kgP46Y8A7DNBEXBX77k1roEc9Tds8b+m+5hFLPuRLib6HZocddZWkklFCSulunvIvbdJSbXTPoQ0dfhhQN1zHRH+id2RsrQPZzQ0NdknBycuhGMB44EYuMmIJpn4CXjfd01tlvmB07yJqUjv+9C/lQd2mm/XYcEm3XXZJ2OXioVrGhNlmVD+Eb4/OwpBrKYJoq1XI9C7MewynU87LcO202Ciivaig9cf6P79mGqHEL3RAH8EzdOmP5mIdpSlKVMLqhjcS2tqY5wZXCa+5GVddwMwuVQksYDl7T6vho3EjDkCZKZaMLMXqgSsqA90+57PMrMPey7Iep/69HjaAFggR2CMQMe/cj27HNKyzL9iWnEETGHWlDR3fDCosd9iD5WneGr13ENSO/KRniGQ8k/AWzcdEaK+IIqm9S71dE+bf38S5XyqxT0X5aLBqz/9kObiJ1Y/LGfc9qAmGemS9CsgaWtyCvuwr+Crq22VACZEr2bM6Oexw2fjvayincllV0yki9iAK/jNt6TQkoK6rv0Wee3TtxfkkA8hSOw/zukXu/RVtPKonqWVyG+Zc1scjbCmcGACSiRdw6pTkZaqrzNg0LUEc=
  on:
    tags: true
    repo: cmr1/node-ts3-bot
notifications:
  slack:
    secure: pZyLZWwcMA2fnNXGC7MmvBVjLZLcOvKnenRXVubY1UdPUkugtprVLDGG28twICHr3eLfJx6NOGquDzklKneD9qZVJ289uJFotc0b1W2PeeIm1iuBD+/mpid9mHmqISdrS5gX/Cv4RzL/Xp92+dMax9JRVKhrBNfDuNA4HNnuac59pj9ufFulK6LZ2fAqzU+ftL4TeLsNszID9aGZ52IOTvEBClj0xespTTOaxMeM1OgHDW87vfGsDog9DaiiCW/Z774L6bEhJifVsB0f2m3PMirepGZHMPCC54ncRi/+o34+fQLOLdfN0y/aXaDoC3Wx0u3FwRqw+uJX11CCMJgGeEdDfTEN/hZ93jDVcK/fWrpommo6LrUBc4K2KRIyPtFgUoMfnm9Cu6Re0zO2SXm++92kSYZpcmYIvC55cZtNSOC6xY6icm1XPdofe+Os3lqQekZXVSqw+pUL6i8ayfaLJV4z6CJQkE4CcInlCxsJUg4YItldKxJDLL7tKjAwUowG1M2dilzuJdbCQjk8dDsZk0KHwO+m8KBdvfyZilV8M+3MmWJ+9ZkQe+XtSIYnXolThk3qkkGhBUUQkJ87Ee9Zo4S+baNJzQiBB3B0zw04ELqtSvAXxgp7pXXtk0YKmpTv27kfH7WN/AS4aVt9z7dHA2eoHHhDm6y7s1ZW5ZTazbQ=
