version: '2'

services:
  ts3:
    image: mbentley/teamspeak
    command: serveradmin_password=password
    environment:
      TS3SERVER_LICENSE: accept
    ports:
      - '10011:10011'
    volumes:
      - /tmp/ts3:/data
